# sig_preload_size == 8000 == max_obs_adapter + search_window + median_shift_window

[llr_boundaries]
sig_norm_winsor_window = 5
sig_norm_outlier_thresh = 5.0

min_obs_adapter = 1500
max_obs_trace = 6500

adapter_trace_tail_trim = 5 # in case of polya determination based on early stopping, this should be a small value
adapter_trace_stride = 20

min_obs_polya = 100

polya_trace_start = 40 # polya_trace_start < min_obs_polya helps with polyA detection
polya_trace_stride = 5

adapter_trace_early_stop_window = 1000
adapter_trace_early_stop_stride = 500
polya_trace_early_stop_window = 100
polya_trace_early_stop_stride = 20

adapter_peak_prominence = 1.0
adapter_peak_rel_height = 1.0
adapter_peak_width = 1000

polya_peak_prominence = 1.0
polya_peak_rel_height = 0.5
polya_peak_width = 50

refine_polya_atol = 20
refine_smooth_sigma = 10

[mvs_polya]
mvs_detect_check = true
mvs_detect_overwrite = false
search_window = 500
pA_mean_window = 20
pA_var_window = 100
pA_var_range = [-inf, 30.0]
median_shift_range = [
    5.0,
    inf,
] # can be removed if pA_mean_adapter_med_scale_range is used?
median_shift_window = 1000
polyA_window = 300 # not used! TODO: remove
polyA_med_range = [-inf, inf]
polyA_local_range = [-inf, inf]

pA_mean_adapter_med_scale_range = [1.3, inf]

[real_range]
detect_open_pores = true
real_signal_check = true
mean_window = 300
mean_start_range = [-inf, inf]
mean_end_range = [-inf, inf]
max_obs_local_range = 5000
local_range = [7.0, 35.0]
adapter_mad_range = [3.0, 12.0]
